on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: example

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} ${{ matrix.config.msystem }}

    defaults:
      run:
        shell: ${{ matrix.config.shell }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest, shell: bash, allow_fail: true }
          - {os: windows-latest, shell: 'msys2 {0}', msystem: MINGW64, allow_fail: false }
          - {os: windows-latest, shell: 'msys2 {0}', msystem: MINGW32, allow_fail: false }
          - {os: ubuntu-18.04, shell: bash, allow_fail: false }
          - {os: ubuntu-16.04, shell: bash, allow_fail: false }

    steps:
      - uses: actions/checkout@v2

      - uses: msys2/setup-msys2@v2
        if: runner.os == 'Windows'
        with:
          msystem: ${{ matrix.config.msystem }}
          install: 'gcc make'

      - name: Check
        run: |
          make check || ${{ matrix.config.allow_fail }}
